---
- project:
    name: model-deployments-deployment-client-info
    project: model-deployments/deployment-client
    project-name: model-deployments-deployment-client
    build-node: centos7-builder-2c-1g
    jobs:
      - gerrit-info-yaml-verify

- project:
    name: model-deployments-deployment-client
    project-name: "{name}"
    project: model-deployments/deployment-client
    mvn-settings: model-deployments-deployment-client-settings
    build-node: centos7-docker-4c-4g
    java-version: openjdk11
    jobs:
      - "{project-name}-gerrit-maven-docker-jobs"
    stream:
      - master:
          branch: master

- project:
    name: model-deployments-deployment-client-release
    project: model-deployments/deployment-client
    project-name: model-deployments-deployment-client
    mvn-settings: model-deployments-deployment-client-settings
    branch: master
    # maven release uses sigul which requires centos
    # container release uses docker
    build-node: centos7-docker-2c-1g
    jobs:
      - "{project-name}-gerrit-release-jobs"
