---
- project:
    name: predictor-management-project
    project-name: predictor-management
    project: predictor-management
    mvn-settings: predictor-management-settings
    python-version: python3
    build-timeout: 30
    concurrent: false
    jobs:
      - '{project-name}-python-jobs'
      - '{project-name}-python-release-{stream}'
      - '{project-name}-python-staging-{stream}'
      - gerrit-maven-clm
    stream:
      - master:
          branch: master
