---
- project:
    name: model-deployments-deployment-client-project
    project-name: model-deployments-deployment-client
    project: model-deployments/deployment-client
    project-settings: model-deployments-deployment-client-settings
    build-node: centos7-docker-4c-4g
    mvn-settings: model-deployments-deployment-client-settings
    python-version: python3
    build-timeout: 30
    concurrent: false
    jobs:
      - '{project-name}-python-jobs'
      - '{project-name}-acumos-docker-jobs'
    stream:
      - master:
          branch: master
      # no athena stream needed

- project:
    name: model-deployments-deployment-client-sonar
    project-name: model-deployments-deployment-client
    project: model-deployments/deployment-client
    mvn-settings: model-deployments-deployment-client-settings
    build-node: centos7-avx-4c-4g
    jobs:
      - gerrit-maven-sonar
    cron: 'H 11 * * *'
    branch: 'master'
    mvn-goals: 'clean install'
    mvn-opts: '-Xmx1024m -XX:MaxPermSize=256m'
