---
- project:
    name: model-deployments-predictor-management-info
    project: model-deployments/predictor-management
    project-name: model-deployments-predictor-management
    build-node: centos7-builder-2c-1g
    jobs:
      - gerrit-info-yaml-verify

- project:
    name: model-deployments-predictor-management
    # jenkins job name prefix
    project-name: "{name}"
    project: model-deployments/predictor-management
    project-settings: model-deployments-predictor-management-settings
    build-node: centos7-docker-4c-4g
    mvn-settings: model-deployments-predictor-management-settings
    python-version: python3
    build-timeout: 30
    concurrent: false
    container-tag-method: yaml-file
    # use host network
    docker-build-args: "--network=host"
    docker-name: acumos/predictor-management
    jobs:
      - "{project-name}-python-jobs"
      - "{project-name}-gerrit-docker-jobs"
    stream:
      - master:
          branch: master
      # no athena stream needed
