---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-json
      - id: trailing-whitespace

  - repo: https://github.com/prettier/prettier
    rev: 2.0.5
    hooks:
      - id: prettier

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.13.1
    hooks:
      - id: gitlint

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.0.2
    hooks:
      - id: shellcheck
        exclude: >
          (?x)^(
              jjb/global-jjb/.*|
              jenkins-config/.*
          )$

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.23.0
    hooks:
      - id: yamllint

  - repo: https://github.com/btford/write-good
    rev: master
    hooks:
      - id: write-good
        exclude: README.md|README.markdown
