DOCKER_REGISTRY=nexus3.acumos.org
GERRIT_URL=https://gerrit.acumos.org/gerrit
GIT_URL=ssh://acumos-jobbuilder@gerrit.acumos.org:29418
JENKINS_HOSTNAME=vex-yul-acumos-jenkins-1
LOGS_SERVER=https://logs.acumos.org
NEXUS_URL=https://nexus.acumos.org
NEXUSPROXY=https://nexus.acumos.org
REGISTRY_PORTS=10001 10002 10003 10004
RELEASE_EMAIL=collab-it+acumos-release@linuxfoundation.org
RELEASE_USERNAME=acumos-release
SIGUL_BRIDGE_IP=10.30.184.3
SIGUL_KEY=acumos-release-2018
SILO=production
SONAR_URL=https://sonar.acumos.org
S3_BUCKET=
