DOCKER_REGISTRY=nexus3.acumos.org
GERRIT_URL=https://gerrit.acumos.org/gerrit
GIT_URL=ssh://acumos-jobbuilder@gerrit.acumos.org:29418
JENKINS_HOSTNAME=vex-yul-acumos-jenkins-2
LOGS_SERVER=https://logs.acumos.org
NEXUS_URL=https://nexus.acumos.org
NEXUSPROXY=https://nexus.acumos.org
REGISTRY_PORTS=10001 10002 10003 10004
RELEASE_EMAIL=collab-it+acumos-release@linuxfoundation.org
RELEASE_USERNAME=acumos-release
S3_BUCKET=
SIGUL_BRIDGE_IP=199.204.45.55
SIGUL_KEY=acumos-sandbox
SILO=sandbox
SONAR_URL=https://sonar.acumos.org
